import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { Plugin } from "vite";
import { de as t } from "../src/i18n/de";

/** Public address of the live app. Link previews need absolute URLs; update this if the app moves. */
export const SITE_URL = "https://lordeisenfaust.github.io/is-it-worth-it/";
const BACKGROUND = "#f4f4f2";
const THEME = "#f26b1d";

/**
 * Makes the build an installable, offline-capable app (PWA), without extra libraries:
 * - emits manifest.webmanifest (texts from the catalog) and links it plus the Apple icon in index.html,
 * - adds a description and link preview tags (Open Graph) for messengers and social networks,
 * - writes sw.js after the build with every file of dist/ in its precache list.
 * The cache name contains version and commit, so each deploy replaces the old cache.
 */
export function pwa(options: { version: string; commit: string }): Plugin {
  let outDir = "dist";
  return {
    name: "lohnt-es-pwa",
    apply: "build",
    configResolved(config) {
      outDir = config.build.outDir;
    },
    transformIndexHtml() {
      const meta = (attrs: Record<string, string>) => ({ tag: "meta", attrs, injectTo: "head" as const });
      return [
        { tag: "link", attrs: { rel: "manifest", href: "./manifest.webmanifest" }, injectTo: "head" },
        { tag: "link", attrs: { rel: "apple-touch-icon", href: "./apple-touch-icon.png" }, injectTo: "head" },
        meta({ name: "description", content: t.app.description }),
        // Link previews (Open Graph, also read by WhatsApp, Signal, Slack, LinkedIn, …).
        meta({ property: "og:type", content: "website" }),
        meta({ property: "og:locale", content: "de_DE" }),
        meta({ property: "og:url", content: SITE_URL }),
        meta({ property: "og:title", content: t.app.title }),
        meta({ property: "og:description", content: t.app.tagline }),
        meta({ property: "og:image", content: `${SITE_URL}og-image.png` }),
        meta({ property: "og:image:width", content: "1200" }),
        meta({ property: "og:image:height", content: "630" }),
        meta({ property: "og:image:alt", content: t.app.previewAlt }),
        meta({ name: "twitter:card", content: "summary_large_image" }),
      ];
    },
    generateBundle() {
      const manifest = {
        name: t.app.title,
        short_name: t.app.title,
        description: t.app.tagline,
        lang: "de",
        start_url: "./",
        scope: "./",
        display: "standalone",
        background_color: BACKGROUND,
        theme_color: THEME,
        icons: [
          { src: "icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      };
      this.emitFile({ type: "asset", fileName: "manifest.webmanifest", source: JSON.stringify(manifest, null, 2) });
    },
    closeBundle() {
      // The link preview image is only fetched by messengers, never by the app itself.
      const files = listFiles(outDir).filter((file) => file !== "sw.js" && file !== "og-image.png");
      const cacheName = `iiwi-${options.version}-${options.commit}`;
      writeFileSync(join(outDir, "sw.js"), serviceWorker(cacheName, ["./", ...files]));
    },
  };
}

function listFiles(dir: string, root = dir): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? listFiles(path, root) : [relative(root, path).split("\\").join("/")];
  });
}

/** Precache everything; pages network-first (fresh when online), other files cache-first (they are hashed). */
function serviceWorker(cacheName: string, files: string[]): string {
  return `// Generated by scripts/pwa-plugin.ts – do not edit.
const CACHE = ${JSON.stringify(cacheName)};
const PREFIX = "iiwi-";
const FILES = ${JSON.stringify(files)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  // Only remove this app's old caches; other apps on the same origin keep theirs.
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put("./", copy));
          }
          return response;
        })
        .catch(() =>
          caches.match("./", { ignoreVary: true }).then((hit) => hit || caches.match("index.html", { ignoreVary: true })),
        ),
    );
    return;
  }

  // ignoreVary: servers answer with e.g. "Vary: Origin", and module scripts are requested with an Origin header
  // that the precache requests lacked; the files are content-hashed, so the cached copy is always right.
  event.respondWith(caches.match(request, { ignoreVary: true }).then((hit) => hit || fetch(request)));
});
`;
}
